config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "bookmarks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	belongs_to :category

	validates :title, presence: true
	validates :host, presence: true
	validates :url, presence: true, uniqueness: true, format: {with: /https?:\/\/[\S]+/}

	validates :category, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:index, :new, :edit, :create, :update]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @q = Bookmark.search(params[:q])
    @bookmarks = @q.result.includes(:category).order("created_at DESC")
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to bookmarks_path, notice: 'Bookmark was successfully created.' }
        format.json { render :show, status: :created, location: @bookmark }
      else
        format.html { render :new }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to bookmarks_path, notice: 'Bookmark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bookmark }
      else
        format.html { render :edit }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :string, :host, :url, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, input_html: {style: "width:250px;"} %>
    <%= f.input :host, input_html: {style: "width:250px;"} %>
    <%= f.input :url, input_html: {style: "width:250px;"} %>
    <%= f.input :category_id, as: :select, collection: @categories.map{|x| [x.name,x.id]},:prompt =>"Select Category", input_html: {style: "width:250px;"} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to 'Cancel', bookmarks_path, class: "btn btn-danger btn-min" %>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<div class="row row-fluid">
	<div class="container">
		<div class="col-sm-12">
			<h1>Edit Bookmark</h1>
			<%= render 'form', bookmark: @bookmark %>
		</div>
	</div>
</div>

app/views/bookmarks/index.html.erb
<div class="container">
  <h4>Bookmarks <%= link_to 'New Bookmark', new_bookmark_path, class: 'btn btn-min btn-primary', style: "float:right" %></h4>
  <br>
  <div class="col-sm-12">
    <%= search_form_for(@q, html: {class: 'form-inline'}) do |f| %>
      <div class="col-sm-12 pull-right">
          <%= f.select(:category_id_eq, options_from_collection_for_select(@categories, "id", "name", @q.category_id_eq), {prompt: "Select Category"}, {class: 'form-control'}) %>
          <%= f.search_field :title_or_host_or_url_cont, placeholder: "Title/Host/URL", class: 'form-control' %>
          <%= f.submit "Search", class: "btn btn-success btn-min"%>
          <%= link_to 'Clear', bookmarks_path, class: 'btn btn-min btn-danger' %>
      </div>
    <% end %>
    <br>
    <% if @bookmarks.blank? %>
      <h4><center><strong>No Bookmarks created yet!</strong></center></h4>
    <% else %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Host</th>
            <th>Url</th>
            <th>Category</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @bookmarks.each do |bookmark| %>
            <tr>
              <td><%= bookmark.title %></td>
              <td><%= bookmark.host %></td>
              <td><%= bookmark.url %></td>
              <td><%= bookmark.category.name %></td>
              <td colspan="3"><%= link_to 'Show', bookmark, class: 'btn btn-min btn-success' %>
                <%= link_to 'Edit', edit_bookmark_path(bookmark), class: 'btn btn-min btn-info' %>
                <%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-min btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="row row-fluid">
	<div class="container">
		<div class="col-sm-12">
			<h1>New Bookmark</h1>
			<%= render 'form', bookmark: @bookmark %>
		</div>
	</div>
</div>

app/views/bookmarks/show.html.erb
<div class="container">
<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Host:</strong>
  <%= @bookmark.host %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category.name %>
</p>
<%= link_to 'Back', bookmarks_path, class: "btn btn-primary btn-min" %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Bookmarks Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Bookmarks <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingWithoutReact</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "layouts/navigation" %>
    <br>
    <% flash.each do |key, value| %>
      <% alert_type = (key=="notice" ? "success" : "error")  %>
      <%= content_tag :div, value, class: "alert alert-#{alert_type} flash #{key}" %>
    <% end %>
    <%= yield %>
  </body>
</html>